#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\pigmentdust.bof
BOFS = 	blackdust.bof   	whitedust.bof \
	   	pinkdust.bof    	reddust.bof 		dreddust.bof \
	   	lbluedust.bof   	bluedust.bof 		dbluedust.bof \
	   	lgreendust.bof  	greendust.bof		dgreendust.bof \
	   	lpurpledust.bof 	purpledust.bof  	dpurpledust.bof \
	   					   	browndust.bof   	dbrowndust.bof \
	   	lyellowdust.bof		yellowdust.bof \
		lorangedust.bof		orangedust.bof		dorangedust.bof \
	


!include $(KODDIR)\kod.mak
