#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\mask.bof
BOFS = antmask.bof kriipmsk.bof ratmask.bof skullmsk.bof trollmsk.bof \
       cowmask.bof daemmask.bof feymask.bof mummymsk.bof xeomask.bof \
       shrnkmsk.bof dratmask.bof strollmsk.bof frontmask.bof ricemask.bof \
       smask.bof tmask.bof wolfmask.bof cmask.bof superstonetrollmask.bof \
       indianhat.bof pilgrimhat.bof feymaskevil.bof rednosemsk.bof carrotnose.bof \
       plaguemask.bof pumpkinmask.bof

!include $(KODDIR)\kod.mak
