#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\crafting.bof
BOFS = cmace.bof  	 	caxe.bof 		cchnarmr.bof	chammer.bof   \
	   civycir.bof 	 	cltharmr.bof 	cshtswrd.bof 	csmllshld.bof \
	   cneruswrd.bof 	cbatbow.bof		ccirclet.bof	cdaemhelm.bof \
	   cgaunts.bof		cgldshld.bof	cgoldshld.bof	chelmet.bof   \
	   ckntshld.bof		clongbow.bof	clongswrd.bof	cmysswrd.bof  \
	   cneruarmr.bof	cnerushld.bof	cpltarmr.bof	cscim.bof	  \
	   csclarmr.bof		capparel.bof	cmagrobe.bof    		      \



!include $(KODDIR)\kod.mak
