#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\ore.bof
BOFS  = qorcitevein.bof diamondvein.bof emeraldvein.bof rubyvein.bof \
		uncutvein.bof sapphirevein.bof neruorevein.bof

!include $(KODDIR)\kod.mak
