#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\skel.bof
BOFS  = batrskel.bof daemskel.bof tuskskel.bof gdaemskel.bof duskskel.bof ghostskel.bof headless.bof


!include $(KODDIR)\kod.mak
