#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\desertdunes.bof

BOFS = desertdunes1.bof desertdunes2.bof desertdunes3.bof desertdunes4.bof \
       desertdunes5.bof desertdunes6.bof desertdunes7.bof desertdunes8.bof \
       desertdunes9.bof desertdunes10.bof desertdunes11.bof desertdunes12.bof
       

!include $(KODDIR)\kod.mak
