#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\enchscrl.bof
BOFS = enchscrlfar.bof enchscrlshal.bof enchscrlkran.bof enchscrlqor.bof enchscrlrii.bof enchscrlblk.bof \

# foflscrl.bof

!include $(KODDIR)\kod.mak
