#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\gift.bof
BOFS = giftarmor.bof giftbow.bof giftgod.bof giftmage.bof giftshield.bof giftweapon.bof \
	   giftdeathrealma.bof giftdeathrealmw.bof giftmask.bof giftinstrument.bof giftclothes.bof \
	   giftdregs.bof giftdweapons.bof giftdmask.bof

!include $(KODDIR)\kod.mak