#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\deathtwn.bof
BOFS  = kailor.bof ceresqor.bof amerantha.bof joline.bof beelzebub.bof celegorm.bof

!include $(KODDIR)\kod.mak
