#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomench.bof
BOFS = shalbane.bof qorbane.bof martyrs.bof darkness.bof heat.bof killing.bof \
       light.bof silence.bof forceslt.bof antimag.bof sandstor.bof truce.bof \
       winds.bof freezing.bof

!include $(KODDIR)\kod.mak
