#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bergrm.bof

BOFS = bergcity.bof bergvault.bof bergsmith.bof berghall.bof bergstore.bof \
       berginn.bof bergbank.bof bergauc.bof bergleader.bof bergleader_hall.bof \
       bergjail.bof berg_devroom.bof

!include $(KODDIR)\kod.mak
