#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\ticket.bof
BOFS = boatticket.bof vaultcont.bof vaultresign.bof xpscroll.bof ubscroll.bof tpscroll.bof

!include $(KODDIR)\kod.mak
