#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bow.bof
BOFS = longbow.bof battlbow.bof pracbow.bof magicbow.bof nerubow.bof qorbow.bof holybow.bof

!include $(KODDIR)\kod.mak
