#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\trestype.bof
BOFS = wimptres.bof notres.bof spquent.bof med-tght.bof wmp-medt.bof \
   tought.bof mediumt.bof ghostt.bof verytght.bof orctres.bof \
   fairytrs.bof entt.bof mummytrs.bof emptytres.bof \
   lowhumt.bof medhumt.bof highhumt.bof rattres.bof ratstres.bof zombiet.bof \
   caveorct.bof orcwizt.bof orcpitt.bof avart.bof avarsht.bof \
   avarcht.bof lupkingt.bof dflyt.bof licht.bof \
   dethspdt.bof skel2t.bof skel3t.bof skel4t.bof narthylt.bof \
   wrmlarvt.bof wrmquent.bof dangelt.bof newbietrs.bof thrasht.bof \
   statuet.bof kriipat.bof molluskt.bof shadowbeastt.bof ratktres.bof \
   earthelet.bof fireelet.bof iceelet.bof neruelet.bof easterbunnyt.bof \
   killerbunnyt.bof xeoairt.bof xeoeartht.bof xeofiret.bof xeowatert.bof \
   xeoacidt.bof xeounholyt.bof xeoholyt.bof xeonerut.bof xeoillt.bof lupoggt.bof necrot.bof \
   earthdragt.bof mimict.bof minotaurt.bof knightt.bof ogret.bof \
   diamondt.bof emeraldt.bof oret.bof qorcitet.bof resplantt.bof restreet.bof \
   rubyt.bof sapphiret.bof trollt.bof densetreet.bof uncutt.bof neruoret.bof \
   dricereavert.bof drobsidianreavert.bof drstonereavert.bof drtyrantt.bof drvajrat.bof \
   drvozunt.bof drredhydrat.bof drgreenhydrat.bof drgoldhydrat.bof drminotaurberserkert.bof \
   drgrandpatrentt.bof drgreenseekert.bof drgreyseekert.bof drblackhydrat.bof \
   drbrownseekert.bof drchimerat.bof drcrocot.bof drcrushersproutt.bof drcyclopst.bof drdeathmitemaget.bof \
   drdeathmitescoutt.bof drdeathmitesoldiert.bof drdeathmitetankt.bof drdulahant.bof drfallenmonkt.bof \
   drfollowerofqort.bof drfrenzysproutt.bof drhellwaspt.bof drrevenantbt.bof drspittersproutt.bof \
   kriipacorpset.bof trollcorpset.bof blackdragt.bof
!include $(KODDIR)\kod.mak
