#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\food.bof
BOFS = inkycap.bof snack.bof watrskin.bof meatpie.bof apple.bof \
       bread.bof mug.bof spideye.bof drumstik.bof pork.bof \
       grapes.bof ftncooky.bof soup.bof goblet.bof gobletst.bof stew.bof \
       gobletwn.bof kocmug.bof cheese.bof mint.bof turkyleg.bof chaosfood.bof \
       cookie.bof pear.bof orange.bof telofruit.bof tikitrib.bof corn.bof \
       pecanpie.bof pumppie.bof mashtaters.bof stuffing.bof ham.bof rouladen.bof \
       qorcite.bof steakmeal.bof gingermen.bof cougarbrew.bof rawsteak.bof \
       tomato.bof banana.bof

!include $(KODDIR)\kod.mak
