#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\helmet.bof
BOFS = helm.bof circlet.bof ivycircl.bof simphelm.bof mask.bof qormashelm.bof \
       dhelm.bof wizardhat.bof knighthelm.bof legionhelm.bof warhelm.bof \
       steelhelm.bof thorncirclet.bof

!include $(KODDIR)\kod.mak
