#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\invasion.bof
BOFS =	ratinvasion.bof orcinvasion.bof easterinvasion.bof spiderinvasion.bof \
	   	skeletoninvasion.bof triggeredinvasion.bof

!include $(KODDIR)\kod.mak
