#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\craftingbench.bof
BOFS = forge.bof loom.bof splitstump.bof craftanvil.bof spinwheel.bof \
       tanrack.bof shavehorse.bof goadanvil.bof kocatananvil.bof kocsplitstmp.bof \
       koctanrack.bof kocatanforge.bof \

!include $(KODDIR)\kod.mak
