#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\deathrealm.bof

BOFS =  dh4.bof dh3.bof di3.bof dbarls.bof dbarln.bof dbarlport.bof \
		dj3.bof dcastle2b.bof dbadland2.bof dbadland1.bof dk5.bof dh5.bof \
		dh6.bof dtos.bof deasttos.bof dtosgrave.bof dtoscrypt.bof dduke1.bof \
		dg4.bof dcornoth.bof df4.bof df3.bof de4.bof dd5.bof dd4.bof dmarion.bof \
		dc5.bof dc4.bof dtemple.bof de2.bof df2.bof dbarlsew.bof dc6.bof dd6e6ulake.bof \
		dd6e6.bof de5.bof dc7.bof dd7.bof de7.bof djaswest.bof djasper.bof df8.bof dg8.bof \
		dg6.bof dh7.bof dg5.bof df7.bof df6.bof di6.bof di7.bof di8.bof di9.bof dh9.bof \
		dg9.bof dtempkra.bof dcastle.bof dcastle1.bof dcastle2.bof dcastle3.bof dcastle4.bof \
		dthrone1.bof dthrone2.bof

!include $(KODDIR)\kod.mak

