#!/bin/bash

pid_file="/tmp/blakserv.pid"
last_sig="/tmp/blakserv.sig"

if [ -f "${pid_file}" ];
then

  PID=$(cat ${pid_file} | xargs echo)

  if ps -p ${PID} > /dev/null
  then
     echo -n "."
     sleep 1
     /runm59
     exit 1
  fi
fi

rm "${pid_file}" -f
rm "${last_sig}" -f

cd /meridian/run/server
wine blakserv.exe & echo $! >> ${pid_file} &
echo ""
echo "Blakserv is running..."
echo ""

wait

rm "${pid_file}" -f
rm "${last_sig}" -f

