#!/bin/bash

PID=0
pid_file="/tmp/blakserv.pid"
last_sig="/tmp/blakserv.sig"
blaklog="/meridian/run/server/channel/log.txt"

if [ -f "${blaklog}" ];
then

  LAST_LOG=$(tail --lines=5 ${blaklog})

  if [[ "${LAST_LOG}" = *"ExitServer"* ]]; then
     rm "${last_sig}" -f
     rm "${pid_file}" -f
  fi
fi

if [ -f "${pid_file}" ];
then
  PID=$(cat ${pid_file} | xargs echo)

  echo ""
  echo "Last PID (Blakserv.exe): ${PID}"
  echo ""

  while s=`ps -p $PID -o s=` && [[ "$s" && "$s" != 'Z' ]]; do

     if [ -f "${blaklog}" ];
     then

        LAST_LOG=$(tail --lines=5 ${blaklog})

        if [[ "${LAST_LOG}" = *"ExitServer"* ]]; then
            rm "${last_sig}" -f
            rm "${pid_file}" -f
            sleep 3
            break
        fi
      fi

      if [ -f "${last_sig}" ];
      then
        LAST_SIGNAL=$(cat ${last_sig} | xargs echo)
        if [ "${LAST_SIGNAL}" != "2" ];
        then
           rm "${last_sig}" -f
           echo ""
           echo "${LAST_SIGNAL} is not 2..."
           echo ""
        fi
      else
         kill -2 ${PID}
         echo ""
         echo "2" > "${last_sig}"
         echo ""
         echo "Requesting blakserv to stop..."
         echo ""
         sleep 2
      fi

      echo -n "-"
      sleep 1
  done
fi

if [ -f "${last_sig}" ];
then
   rm "${last_sig}" -f
   echo ""
   echo "Clearing last signal file..."
   echo ""
fi

cat /tmp/.X1-lock | xargs kill -1
pkill blakserv
pkill wine
pkill .exe
pkill Xvfb
sleep 1

