#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\deathrealmM.bof
BOFS  = vajra.bof revenantb.bof chimera.bof cyclops.bof followerofqor.bof \
		minotaurbeserker.bof Tyrant.bof fallenmonk.bof hellwasp.bof vozun.bof \
		croco.bof dulahan.bof grandpatrent.bof spittersprout.bof crushersprout.bof \
		frenzysprout.bof blackhydra.bof redhydra.bof goldhydra.bof greenhydra.bof \
		greyseeker.bof greenseeker.bof brownseeker.bof dthmitemage.bof dthmitescout.bof \
		dthmitesold.bof dthmitetank.bof stonereaver.bof icereaver.bof obsidianreaver.bof



!include $(KODDIR)\kod.mak
