#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\skill.bof
BOFS = profic.bof stroke.bof dodge.bof parry.bof assess.bof block.bof \
	   secwind.bof disarm.bof gathering.bof logging.bof mining.bof \
	   skinning.bof

!include $(KODDIR)\kod.mak
